export default {
    SET_STATUS: 'SET_STATUS',
    SET_AUTH_RESULT: 'SET_AUTH_RESULT',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_STATUS_SAGA: 'SET_STATUS_SAGA',
    SET_AUTH_RESULT_SAGA: 'SET_AUTH_RESULT_SAGA',
    SET_ACCESS_TOKEN_SAGA: 'SET_ACCESS_TOKEN_SAGA'
}