export default {
    SET_STATUS: 'SET_STATUS',
    SET_AUTH_RESPONSE: 'SET_AUTH_RESPONSE',
    SET_STATUS_SAGA: 'SET_STATUS_SAGA',
    SET_AUTH_RESPONSE_SAGA: 'SET_AUTH_RESPONSE_SAGA',
    SET_FB: 'SET_FB',
}