export default {
    SET_USER_PAGES: 'SET_USER_PAGES',
    SET_PAGE_POSTS: 'SET_PAGE_POSTS',
    SET_SELECTED_PAGE: 'SET_SELECTED_PAGE',
    SET_SELECTED_POST: 'SET_SELECTED_POST',
    SET_POST_COMMENTS: 'SET_POST_COMMENTS',
}