export default {
    SET_BUSINESS_ID: "SET_BUSINESS_ID",
    SET_MEDIAS: "SET_MEDIAS",
    SET_SELECTED_MEDIA: "SET_SELECTED_MEDIA",
    SET_COMMENTS: "SET_COMMENTS",
    RESET_STATE: 'RESET_STATE',
}