export default {
    ADD_LIST: "ADD_LIST",
    REMOVE_LIST: "REMOVE_LIST",
    EDIT_LIST_NAME: "EDIT_LIST_NAME",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    EDIT_ITEM_NAME: "EDIT_ITEM_NAME",
    SET_ITEM_ENABLED_STATE: "SET_ITEM_ENABLED_STATE",
}